//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um Xland.
        /// </summary>
        public static string AboutXland {
            get {
                return ResourceManager.GetString("AboutXland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samstarfsaðilar.
        /// </summary>
        public static string Affiliations {
            get {
                return ResourceManager.GetString("Affiliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allt.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svæði.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stærð.
        /// </summary>
        public static string AreaSize {
            get {
                return ResourceManager.GetString("AreaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til baka.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stofnkostnaður.
        /// </summary>
        public static string CapitalCost {
            get {
                return ResourceManager.GetString("CapitalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flokkur.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veldu flokk.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veldu tungumál.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samkeppnir.
        /// </summary>
        public static string Competitions {
            get {
                return ResourceManager.GetString("Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tengiliður.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkkaupi.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lýsing.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lýsing á ensku.
        /// </summary>
        public static string DescriptionEnglish {
            get {
                return ResourceManager.GetString("DescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hönnuðir.
        /// </summary>
        public static string Designers {
            get {
                return ResourceManager.GetString("Designers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almennar upplýsingar.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saga.
        /// </summary>
        public static string Historical {
            get {
                return ResourceManager.GetString("Historical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breiddargráða.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svæði.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengdargráða.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkefni lokið.
        /// </summary>
        public static string ProjectFinished {
            get {
                return ResourceManager.GetString("ProjectFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staðsetning.
        /// </summary>
        public static string ProjectLocation {
            get {
                return ResourceManager.GetString("ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkkaupi.
        /// </summary>
        public static string ProjectOwner {
            get {
                return ResourceManager.GetString("ProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkefni hafið.
        /// </summary>
        public static string ProjectStarted {
            get {
                return ResourceManager.GetString("ProjectStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staða verkefnis.
        /// </summary>
        public static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tegund verkefnis.
        /// </summary>
        public static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almenninsrými.
        /// </summary>
        public static string PublicSpaces {
            get {
                return ResourceManager.GetString("PublicSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipulag.
        /// </summary>
        public static string Regional {
            get {
                return ResourceManager.GetString("Regional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stofur.
        /// </summary>
        public static string Studios {
            get {
                return ResourceManager.GetString("Studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stofur og Þáttakendur.
        /// </summary>
        public static string StudiosAndParticipants {
            get {
                return ResourceManager.GetString("StudiosAndParticipants", resourceCulture);
            }
        }
    }
}
